set_property SRC_FILE_INFO {cfile:C:/Users/tuamy/Documents/GitHub/EE89-Poj1/project_2/project_2.srcs/constrs_1/imports/basys3_master/Basys3_Master.xdc rfile:../../../project_2.srcs/constrs_1/imports/basys3_master/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports clk_led]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports rst]
